/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.temp.monitor;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SomeUtilTest {
    @Test void foo() {
        assertEquals(true, true);
    }
}
